[buildPlans.IosevkaCode]
family = "Iosevka Code"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.IosevkaCode.variants]
  inherits = "ss04"

    [buildPlans.IosevkaCode.variants.design]
    zero = "slashed"
    one = "base"
    tilde = "low"
    asterisk = "hex-low"
    ascii-single-quote = "straight"
    brace = "straight"
    number-sign = "upright"
    ampersand = "closed"
    cent = "through"
    percent = "rings-continuous-slash"
    question = "corner"
    partial-derivative = "curly-bar"
    lig-equal-chain = "with-notch"
    lig-hyphen-chain = "with-notch"
    lig-double-arrow-bar = "without-notch"

[buildPlans.IosevkaCode.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaCode.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCode.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IosevkaCode.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.IosevkaCode.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaCode.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaCode.widths.UltraCondensed]
shape = 416
menu = 1
css = "ultra-condensed"

[buildPlans.IosevkaCode.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaCode.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"